version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: my_mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: metr.club
      MYSQL_USER: bereg
      MYSQL_PASSWORD: 2000
    volumes:
      - ./mysql-data:/var/lib/mysql
